apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: acns-security-agent
  labels:
    k8s-app: acns-security-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: acns-security-agent
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "9961"
        prometheus.io/scrape: "true"
      labels:
        k8s-app: acns-security-agent
    spec:
      automountServiceAccountToken: false
      priorityClassName: system-node-critical
      containers:
        - name: fqdn-policy
          image: $CILIUM_IMAGE_REGISTRY/cilium/dns-proxy:$SDP_VERSION_TAG
          args:
          - --config-dir=/tmp/fqdn-policy/config-map
          livenessProbe:
            tcpSocket:
              host: "127.0.0.1"
              port: 40046
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              host: "127.0.0.1"
              port: 40046
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          volumeMounts:
          - mountPath: /tmp/fqdn-policy/config-map
            name: fqdn-policy-config-path
            readOnly: true
          - mountPath: /var/run/cilium
            name: cilium-run
          - name: bpf-maps
            mountPath: /sys/fs/bpf
          securityContext:
            capabilities:
              drop: ["ALL"]
              add: ["BPF", "NET_ADMIN", "NET_RAW"]
      volumes:
      - name: cilium-run
        hostPath:
          path: /var/run/cilium
      - name: bpf-maps
        hostPath:
          path: /sys/fs/bpf
      - configMap:
          defaultMode: 420
          name: fqdn-policy-config
        name: fqdn-policy-config-path
      hostNetwork: true