apiVersion: v1
data:
  enable-l7-proxy: "true"
  enable-ipv4: "true"
  enable-ipv6: "false"
  tofqdns-proxy-port: "40046"
  tofqdns-server-port: "10095"
  tofqdns-endpoint-max-ip-per-hostname: "1000"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: fqdn-policy
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
  name: fqdn-policy-config
  namespace: kube-system