{{$PROMETHEUS_SCRAPE_KUBELETS := DefaultParam .PROMETHEUS_SCRAPE_KUBELETS false}}

{{if $PROMETHEUS_SCRAPE_KUBELETS}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: kubelet
  name: kubelet
  namespace: monitoring
spec:
  jobLabel: k8s-app
  endpoints:
  - port: https-metrics
    scheme: https
    interval: 60s
    tlsConfig:
      insecureSkipVerify: true
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    metricRelabelings:
      - sourceLabels: [__name__]
        regex: kubelet_pod_start_total_duration_seconds.*|kubelet_pod_start_sli_duration_seconds.*|kubelet_run_podsandbox.*|kubelet_pod_start_duration_seconds.*|kubelet_runtime_operations.*
        action: keep
  - port: https-metrics
    scheme: https
    path: /metrics/cadvisor
    interval: 30s
    honorLabels: true
    tlsConfig:
      insecureSkipVerify: true
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      #metricRelabelings:
      #- sourceLabels: [__name__]
      # regex: kubelet.*
      # action: drop
          #- sourceLabels: [__name__]
          #regex: 'kubelet_pod_start_total_duration_seconds.*|kubelet_pod_start_sli_duration_seconds.*|kubelet_run_podsandbox.*|kubelet_pod_start_duration_seconds.*'
          #action: keep
          #- sourceLabels: [ namespace ]
          #regex: 'test-.*'
          #action: drop
  selector:
    matchLabels:
      k8s-app: kubelet
  namespaceSelector:
    matchNames:
    - kube-system
{{end}}
