apiVersion: v1
kind: ConfigMap
metadata:
  name: hubble-relay-config
  namespace: kube-system
data:
  config.yaml: |
    cluster-name: default
    peer-service: "hubble-peer.kube-system.svc.cluster.local:443"
    listen-address: :4245
    gops: true
    gops-port: "9893"
    tls-hubble-client-cert-file: /var/lib/hubble-relay/tls/client.crt
    tls-hubble-client-key-file: /var/lib/hubble-relay/tls/client.key
    tls-hubble-server-ca-files: /var/lib/hubble-relay/tls/hubble-server-ca.crt
    tls-relay-server-cert-file: /var/lib/hubble-relay/tls/server.crt
    tls-relay-server-key-file: /var/lib/hubble-relay/tls/server.key
    tls-relay-client-ca-files: /var/lib/hubble-relay/tls/hubble-server-ca.crt