{{$PROMETHEUS_SCRAPE_ETCD := DefaultParam .PROMETHEUS_SCRAPE_ETCD false}}
{{$PROMETHEUS_SCRAPE_MASTER_KUBELETS := DefaultParam .PROMETHEUS_SCRAPE_MASTER_KUBELETS false}}
{{$PROMETHEUS_SCRAPE_NODE_EXPORTER := DefaultParam .PROMETHEUS_SCRAPE_NODE_EXPORTER false}}
{{$PROMETHEUS_SCRAPE_APISERVER_ONLY := DefaultParam .PROMETHEUS_SCRAPE_APISERVER_ONLY false}}

# If kube-apiserver is overloaded, we might get slower responses.
{{$PROMETHEUS_SLOW_APISERVER := DefaultParam .CL2_PROMETHEUS_SLOW_APISERVER false}}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: master
  name: master
  namespace: monitoring
spec:
  endpoints:
  {{if $PROMETHEUS_SCRAPE_ETCD}}
  - interval: 5s
    port: etcd-2379
  - interval: 5s
    port: etcd-2382
  {{end}}
  {{if $PROMETHEUS_SCRAPE_NODE_EXPORTER}}
  # TODO(mborsz): Debug why node-exporter is that slow and change interval back to 5s.
  - interval: 30s
    port: node-exporter
    scrapeTimeout: 20s
  {{end}}
  - port: apiserver
    scheme: https
    bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    tlsConfig:
      insecureSkipVerify: true
      caFile: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
  {{if $PROMETHEUS_SLOW_APISERVER}}
    interval: 30s
    scrapeTimeout: 30s
  {{else}}
    interval: 5s
  {{end}}
    metricRelabelings:
      - sourceLabels: [__name__]
        regex: apiserver_request_total|apiserver_request_duration_seconds_bucket|apiserver_request_terminations_total|apiserver_storage_objects|apiserver_storage_list_fetched_objects_total|apiserver_storage_list_duration_seconds_bucket|apiserver_current_inflight_requests|apiserver_current_inqueue_requests|apiserver_longrunning_requests|apiserver_watch_events_total|workqueue_depth|workqueue_adds_total|workqueue_work_duration_seconds_bucket
        action: keep
  {{if $PROMETHEUS_SCRAPE_MASTER_KUBELETS}}
  - interval: 5s
    port: kubelet
    scheme: https
    bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    tlsConfig:
      insecureSkipVerify: true
      caFile: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
  - interval: 5s
    port: kubelet
    path: /metrics/cadvisor
    scheme: https
    bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    tlsConfig:
      insecureSkipVerify: true
      caFile: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    metricRelabelings:
      - sourceLabels: [__name__]
        regex: container_cpu_usage_seconds_total|container_memory_working_set_bytes|container_memory_usage_bytes|container_cpu_cfs_throttled_periods_total|container_cpu_cfs_periods_total
        action: keep
      - sourceLabels: [container]
        regex: kube-apiserver|cilium-agent|cilium-operator|apiserver|etcd|kvstoremesh
        action: keep
  {{end}}
  {{if not $PROMETHEUS_SCRAPE_APISERVER_ONLY}}
  # - interval: 5s
  #   port: kube-scheduler
  #   scheme: https
  #   tlsConfig:
  #     insecureSkipVerify: true
  # - interval: 5s
  #   port: kube-controller-manager
  #   scheme: https
  #   tlsConfig:
  #     insecureSkipVerify: true
  {{end}}
  selector:
    k8s-app: master
